[package]
name = "codecrafters-kafka"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
thiserror = "1.0.38"
tokio = { version = "1.42.0", features = ["net", "io-util", "rt", "rt-multi-thread", "macros"] }
